# Generated by Django 4.2.23 on 2025-07-09 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='age',
            new_name='idade',
        ),
    ]
